### PR TITLE
Feature Voting Slider Modal for Users When Not Logged In

### LINKED ISSUE #340: Voting Slider Issue For Not Logged Users
If the user is logged out, voting slider shows NaN as value. Instead it should show a modal to invite the user to either go to signup.utopian.io or to login with SteemConnect.

### PR DESCRIPTION
**Pull request by caleblogan**
closes #340

I hardcoded the the signup location as I wasn't sure where that should go.

### CODE REVIEW

**Comment by wehmoen** [comment]
Could you please wait before a task is assigned to you? I was already writing to another developer about this task. :)

**Comment by caleblogan** [comment]
Sure. Sorry about that. Ill contact you on discord in the future first.

**Comment by wehmoen** [comment]
You can use https://tasks.utopian.info to find some open tasks. Comment that you want to do this task and someone will assign this task to you. :) After that you can start with the coding.

**Comment by caleblogan** [comment]
Thanks for the link! I didn't know this existed.

**Pull request merged**
