### PR TITLE
Feature/moderator inline edit category

### PR DESCRIPTION
**Pull request by eastmaels**

### CODE REVIEW

**Comment by wehmoen** [comment]
@eastmaels can you take care of the merge conflict please? :)

**Comment by wehmoen** [comment]
Waiting for https://github.com/utopian-io/api.utopian.io/pull/96 to get merged

**Comment by eastmaels** [comment]
This is noted. Currently out now. Will resolve when i  get home.

**Comment by eastmaels** [comment]
Hello @wehmoen, I've resolved the conflicts. Please check.

**Pull request merged**
