### PR TITLE
Add Feature to Allow Using #Tags in Search

### PR DESCRIPTION
**Pull request by caleblogan**
ref #358 

I added the hash to the query string to allow searching github by tags. Both search endpoints urlencode `q` later on.

### CODE REVIEW

**Comment by azarus** [comment]
Hi can you also add that so hastags search for steemit tags in posts?

**Comment by azarus** [comment]
As in the ref there was a related issue:
https://github.com/utopian-io/utopian.io/issues/26

**Comment by caleblogan** [comment]
Sure, I'll do that today.

**Comment by caleblogan** [comment]
Instead of filtering tags on the client, I sent the tags in the `bySimilarity` param. This is how it gets sent to github so I thought it would be more consistent. This pull request adds the necessary filtering on the backend: utopian-io/api.utopian.io#94

**Comment by caleblogan** [comment]
I didn't add the ability to click a tag and automatically search by that tag. Should that be part of this pull request or another one?

**Pull request merged**
