### PR TITLE
Bugfix/block user displays in own profile

### PR DESCRIPTION
**Pull request by eastmaels**
Merge fix from busyorg/busy. Original PR by @mktcode:
https://github.com/busyorg/busy/pull/852

### CODE REVIEW

**Comment by mktcode** [comment]
Thanks! I actually added this https://github.com/utopian-io/utopian.io/pull/2 but it still has a bug that I fixed in https://github.com/busyorg/busy/pull/852/commits/f787d3df5ad4e6b6b37b0f9483b3f5dd4cb2254a. So your PR can be merged.

**Comment by eastmaels** [comment]
Ok, thanks. I tried comparing it and it's the `authenticated` right?

**Comment by mktcode** [comment]
Yes. For some reason the left sidebar behaves strange when `authenticated` is also checked. But since it's already checked in `isSameUser` I removed it and everything was nice again. :)

**Comment by eastmaels** [comment]
Cool. thanks for the update. I'm only starting to learn React and Redux (i understand javascript), making this PR somehow walked me through in understanding the content of the fix.

**Comment by mktcode** [comment]
I too have no experience with react... but how hard can it be? :P

**Pull request merged**
