### PR TITLE
Fix contribution button on front page #220

### PR DESCRIPTION
**Pull request by kirkins**
I noticed this same issue when trying to submit a contribution today.

I'm pretty sure it was just a small typo.

I'm having trouble getting Steem connect to work on the dev-server. Has anyone had success with that? 

#220

### CODE REVIEW

**Comment by wehmoen** [comment]
We dont accept pull requests on the master branch.
We dont accept untested code.
Have a look at our tutorial how to setup utopian on your local environment: 
https://steemit.com/utopian-io/@utopian-io/how-to-run-utopian-io-in-your-local-machine-here-is-how

**Comment by kirkins** [comment]
Ok, I will setup the backend. 

You want me to make a PR to develop?

**Comment by kirkins** [comment]
:/ I don't really want to pay 3 Steem to make a SteemConnect account.

untitled

Is there any other way to test this?

**Comment by wehmoen** [comment]
To properly setup utopian you need a steemconnect app.

**Comment by kirkins** [comment]
@wehmoen 

1. Thanks for making it so easy to contribute to this repository :-)

2. Super glad they put a master programmer like you in charge.

**Pull request closed without merging**
